networks:
  web:
    external: true
  backend:
    external: true
volumes:
  Hosting:
    external: true
services:
  php:
    build: 
      context: './Build/php/'
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - www=${www}
    networks:
      - backend
    volumes:
      - ${localstorage}:${root}
    working_dir: ${root}
    container_name: "Php.${site_name}"
  apache:
    hostname: ${domain} 
    build: 
      context: ./Build/apache
    depends_on:
      - php
    networks:
      - web
      - backend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - www=${www}
      - APACHE_VERSION=${APACHE_VERSION}
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.${site_name}_web.rule=Host(`${domain}`)"
    #   - "traefik.http.routers.${site_name}_web.entrypoints=web"
    #   - "traefik.http.routers.${site_name}_websecure.rule=Host(`${domain}`)"
    #   - "traefik.http.routers.${site_name}_websecure.entrypoints=websecure"
    #   - "traefik.http.routers.${site_name}_websecure.tls.certresolver=myresolver"
    #   - "traefik.docker.network=web"
    working_dir: ${root}
    volumes:
      - ${localstorage}:${root}
    container_name: "Apache.${site_name}"

