networks:
  web:
    external: true
  backend:
    external: true
  traefik:
    external: true
volumes:
  Hosting:
    external: true
services:
  php:
    build: 
      context: './Build/php/'
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - www=${www}
    networks:
      - backend
    volumes:
      - ${localstorage}:${root}
    working_dir: ${root}
    container_name: "Php.${site_name}"
    restart: "always"
  apache:
    hostname: ${domain}
    image: test/test:beta
    depends_on:
      - php
    networks:
      - web
      - traefik
      - backend
    environment:
      - APACHE_VERSION=${APACHE_VERSION}
      - domain=${domain}
      - www=${www}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${site_name}_web.rule=Host(`${domain}`)"
      - "traefik.http.routers.${site_name}_web.entrypoints=web"
      - "traefik.http.routers.${site_name}_websecure.rule=Host(`${domain}`)"
      - "traefik.http.routers.${site_name}_websecure.entrypoints=websecure"
      - "traefik.http.routers.${site_name}_websecure.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik"
      
    working_dir: ${root}
    restart: "always"
    volumes:
      - ${localstorage}:${root}
    container_name: "Apache.${site_name}"

